### ISSUE TITLE
TinyLLaMa is to heavy for GH

### ISSUE THREAD

**Issue by godricgugly** [ElissaCusson/MethodMIND#6]
Downloading the TinyLLaMa model makes  the folder to heavy for GH. Haven't located where this weight gets stored, so it could be added to gitignore. 

at the moment download the model only outside the pyenv and folder structure.

other option is to use the model only through google collab (gives access to GPUs also!).

**Comment by jmas3p** [comment]
Fixed in the LLM_Local_Ignore branch
